[welcome]
id = 1192500
title = 'Introduction to NationStates and the South Pacific (Click here if you are new!)'
category = 8
sub_category = 835

[index]
id = 1237123
title = "Index to every dispatch about the South Pacific"
category = 8
sub_category = 835

[government_intro]
id = 1192502
title = 'Introduction to the Government of the South Pacific'
category = 8
sub_category = 835

[factbook]
id = 1192534
title = "The Coalition of the South Pacific's Factbook"
category = 8
sub_category = 835

[get_involved]
id = 1192503
title = 'Get Involved in the South Pacific'
category = 8
sub_category = 835

[guide_index]
id = 1230616
title = 'List of guides about NationStates and the South Pacific'
category = 8
sub_category = 835

[government_jobs]
id = 1205787
title = 'Get a job in the Government of the South Pacific'
category = 8
sub_category = 835

[elections]
id = 1192504
title = 'Elections in the South Pacific'
category = 8
sub_category = 835

[news_outlets]
id = 1192505
title = 'List of news outlets in the South Pacific'
category = 8
sub_category = 835

[elections_guide]
id = 1192516
title = 'Beginner guide to Elections in the South Pacific'
category = 8
sub_category = 835

[elections_voting_methods]
id = 1192517
title = 'Election voting methods explained'
category = 8
sub_category = 835

[ns_guide]
id = 1192532
title = 'Full Guide to NationStates'
category = 8
sub_category = 835

[politics_guide]
id = 1199302
title = 'Beginner guide to politics in the South Pacific'
category = 8
sub_category = 835

[assembly_intro]
id = 1192506
title = 'The Assembly of the South Pacific'
category = 8
sub_category = 835

[become_legislator]
id = 1192507
title = 'Become a Legislator in the South Pacific!'
category = 8
sub_category = 835

[assembly_guide]
id = 1192509
title = 'Beginner guide to the Assembly of the South Pacific'
category = 8
sub_category = 835

[assembly_procedures]
id = 1192510
title = 'Legislative Procedures of the Assembly of the South Pacific'
category = 8
sub_category = 835

[assembly_details]
id = 1192515
title = 'Details on the powers of the Assembly of the South Pacific'
category = 8
sub_category = 835

[cabinet_intro]
id = 1192519
title = 'The Executive branch of the South Pacific'
category = 8
sub_category = 835

[cabinet_elections]
id = 1192520
title = 'Cabinet elections in the South Pacific'
category = 8
sub_category = 835

[cabinet_details]
id = 1192521
title = 'Details on the working of the Executive branch'
category = 8
sub_category = 835

[court_intro]
id = 1192522
title = 'The High Court of the South Pacific'
category = 8
sub_category = 835

[court_details]
id = 1192523
title = 'Details on the powers of the High Court of the South Pacific'
category = 8
sub_category = 835

[court_procedures]
id = 1192524
title = 'Procedures of the High Court of the South Pacific'
category = 8
sub_category = 835

[court_guide]
id = 1192525
title = 'Beginner guide to the High Court of the South Pacific'
category = 8
sub_category = 835

[indie_intro]
id = 1205793
title = 'Independent institutions of the South Pacific'
category = 8
sub_category = 835

[crs_intro]
id = 1192526
title = 'The Council on Regional Security of the South Pacific'
category = 8
sub_category = 835

[endo_cap]
id = 1192558
title = 'The Endorsement Cap in the South Pacific'
category = 8
sub_category = 835

[proscriptions]
id = 1220344
title = 'Regions proscribed by the South Pacific'
category = 8
sub_category = 835

[legcomm]
id = 1192527
title = 'The Legislator Committee of the South Pacific'
category = 8
sub_category = 835

[election_commission]
id = 1212829
title = "The Election Commission of the South Pacific"
category = 8
sub_category = 835

[coa]
id = 1192528
title = 'The Chair of Assembly of the South Pacific'
category = 8
sub_category = 835

[delegate_intro]
id = 1192529
title = 'The Delegate of the South Pacific'
category = 8
sub_category = 835

[delegate_details]
id = 1192530
title = 'Details on the working of the Delegate of the South Pacific'
category = 8
sub_category = 835

[delegate_elections]
id = 1192531
title = 'Delegate elections in the South Pacific'
category = 8
sub_category = 835

[law_index]
id = 1192536
title = "The South Pacific's Law Index"
category = 8
sub_category = 835
