[treaties_act]
title = "Treaties Act - TSP"
category = 8
sub_category = 835

[charter]
title = "The Charter of the South Pacific"
category = 8
sub_category = 835

[elections_act]
title = "The Elections Act - TSP"
category = 8
sub_category = 835

[legislator_committee_act]
title = "Legislator Committee Act - TSP"
category = 8
sub_category = 835

[legislative_procedure_act]
title = "Legislative Procedure Act - TSP"
category = 8
sub_category = 835

[law_standards_act]
title = "Law Standards Act - TSP"
category = 8
sub_category = 835

[criminal_code]
title = "Criminal Code - TSP"
category = 8
sub_category = 835

[regional_communications_act]
title = "Regional Communications Act - TSP"
category = 8
sub_category = 835

[proscription_act]
title = "Proscription Act - TSP"
category = 8
sub_category = 835

[judicial_act]
title = "Judicial Act - TSP"
category = 8
sub_category = 835

[holidays_act]
title = "Holidays Act - TSP"
category = 8
sub_category = 835

[sunshine_act]
title = "Sunshine Act - TSP"
category = 8
sub_category = 835

[political_parties_act]
title = "Political Parties Act - TSP"
category = 8
sub_category = 835

[border_control_act]
title = "Border Control Act - TSP"
category = 8
sub_category = 835

[military_code]
title = "Military Code - TSP"
category = 8
sub_category = 835

[regional_officers_act]
title = "Regional Officers Act - TSP"
category = 8
sub_category = 835
