[gov_officials]
delegate = 'Amerion'
local_council = ['Drystar', 'Volaworand', 'Beepee']
crs = ['Sandaoguo', 'Farengeto', 'Kringalia', 'Erinor', 'Tsunamy', 'Aumeltopia', 'Amerion', 'Qvait', 'PenguinPies']
legcomm = ['Roavin', 'PenguinPies', 'FiHami']
general_corps = ['Roavin', 'Nakarisaune']
mora_advisory_council = ['MoRA is dead']
cabinet_advisors = ['Sandaoguo', 'Roavin']
coa = 'Purple Hyacinth'
pm = 'PenguinPies'
mora = 'MoRA is dead'
mofa = 'United Federated States of Omega'
moma = 'FiHami'
hc_chief_justice = 'Kringalia'
hc_justices = ['Kringalia', 'Belschaft', 'Griffindor']
election_commissioner = 'Tsunamy'

[test]
region_nation_num = 8000

[misc]
secret_ballot_forum_acc = 'The Vote Collector'
news_outlet_adder = 'United States of Vietnam'