[urls]
f_bantam_harbour = 'https://tspforums.xyz/forum-109.html'
f_bantam_harbour_map = 'https://tspforums.xyz/thread-241.html'
f_knowhere = 'https://tspforums.xyz/forum-292.html'
f_spam = 'https://tspforums.xyz/forum-14.html'
f_news = 'https://tspforums.xyz/forum-22.html'
f_crs = 'https://tspforums.xyz/forum-53.html'
f_cabinet_twitter = 'https://tspforums.xyz/thread-6621.html'
f_executive_offices = 'https://tspforums.xyz/forum-32.html'
f_assembly_archive = 'https://tspforums.xyz/forum-91.html'
roleplay_intro = 'https://www.nationstates.net/page=dispatch/id=920399'
f_wa = 'https://tspforums.xyz/forum-35.html'
forum = 'https://tspforums.xyz/index.php'
rmb = 'https://www.nationstates.net/page=display_region_rmb/region=the_south_pacific'
discord = 'https://discordapp.com/invite/tEyyDyh'
ns_faq = 'https://www.nationstates.net/page=faq'
ns_wa = 'https://www.nationstates.net/page=un'
ns_telegram = 'https://www.nationstates.net/page=telegrams'
ns_nation_census = 'https://www.nationstates.net/page=list_nations/mode=g?censusid=0'
ns_pol_faq = 'https://www.nationstates.net/page=faq#politics'
ns_codes = 'https://www.nationstates.net/page=dispatch/id=330837'
ns_issue_types = 'https://www.nationstates.net/page=dispatch/id=299923'
ns_tools = 'https://www.nationstates.net/page=dispatch/id=219095'
nsf_got_issues = 'https://forum.nationstates.net/viewforum.php?f=13&sid=0723b6b72ddc34d1d0986556306443cd'
secret_ballot_forum_acc = 'https://tspforums.xyz/user-73.html'
lc_intro = 'https://www.nationstates.net/page=dispatch/id=1199328'
rmb_rules = 'https://www.nationstates.net/page=dispatch/id=1199335'
lc_policies = 'https://www.nationstates.net/page=dispatch/id=1199330'
lc_elections = 'https://www.nationstates.net/page=dispatch/id=1186281'
f_assembly_office = 'https://tspforums.xyz/thread-5131.html'
court_orcs = 'https://tspforums.xyz/forum-393.html'
f_legislator_signup = 'https://tspforums.xyz/forum-11.html'
f_assembly_hall = 'https://tspforums.xyz/forum-27.html'
f_private_assembly_hall = 'https://tspforums.xyz/forum-28.html'
f_voting_chamber = 'https://tspforums.xyz/forum-29.html'
f_legislator_signup_faq = 'https://tspforums.xyz/thread-5837-post-188674.html#pid188674'
f_legislator_loa = 'https://tspforums.xyz/thread-5838.html'
f_create_legislator_signup_thread = 'https://tspforums.xyz/newthread.php?fid=11'
f_legislator_signup_thread = 'https://tspforums.xyz/thread-5837.html'
f_pm_office = 'https://tspforums.xyz/forum-32.html'
f_assembly_coc = 'https://tspforums.xyz/thread-6910.html'
f_assembly_info = 'https://tspforums.xyz/thread-7333.html'
f_matt_duck = 'https://tspforums.xyz/forum-31.html'
swan_intro = 'https://www.nationstates.net/page=dispatch/id=1042647'
swan_guide = 'https://www.nationstates.net/page=dispatch/id=1048440'
swan_benefits = 'https://www.nationstates.net/page=dispatch/id=1050443'
swan_knights = 'https://www.nationstates.net/page=dispatch/id=1045928'
swan_awards = 'https://www.nationstates.net/page=dispatch/id=1054975'
swan_progress = 'https://www.nationstates.net/page=dispatch/id=1043675'
swan_portrait = 'https://www.nationstates.net/page=dispatch/id=1042161'
swan_stats = 'https://www.nationstates.net/page=dispatch/id=1043852'
swan_faq = 'https://www.nationstates.net/page=dispatch/id=1049890'